# ingress-nginx-instana.yaml

imagePullSecrets:
  - name: instana-registry-key

controller:

  config: { enable-opentracing: "true", http-snippet: "
    server {
      listen 18080;
      location /nginx_status {
        stub_status on;
        access_log  off;
      }
      location / {
        return 404;
      }
    }"
  }

  extraEnvs:
    - name: INSTANA_SERVICE_NAME
      value: "ingress-nginx-demo"
    - name: INSTANA_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: INSTANA_AGENT_PORT
      value: "42699"
    - name: INSTANA_MAX_BUFFERED_SPANS
      value: "1000"
#    - name: INSTANA_DEV
#      value: "1"

  extraVolumes:
    - name: instana-tracing-dependencies
      emptyDir: {}
    - name: instana-nginx-template
      emptyDir: {}

  extraVolumeMounts:
    - name: instana-tracing-dependencies
      mountPath: /instana/nginx
    - name: instana-nginx-template
      mountPath: /etc/nginx/template

  extraInitContainers:
    - name: instana-tracing-dependencies
      image: containers.instana.io/instana/release/agent/ingress-nginx-init:latest-ingress-nginx-2.11.1
      imagePullPolicy: Always
      volumeMounts:
        - name: instana-tracing-dependencies
          mountPath: /instana/nginx
        - name: instana-nginx-template
          mountPath: /etc/nginx/template

# vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab :